AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SolcastFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.handler
      Runtime: nodejs14.x
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_PORT: !Ref DBPort
          DB_USERNAME: !Ref DBUsername
          DB_PASSWORD: !Ref DBPassword
          DB_DATABASE: !Ref DBDatabase
          SOLCAST_API_KEY: !Ref SolcastApiKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /weather
            Method: get
Parameters:
  DBHost:
    Type: String
    Default: localhost
  DBPort:
    Type: String
    Default: '5432'
  DBUsername:
    Type: String
    Default: your_username
  DBPassword:
    Type: String
    Default: your_password
  DBDatabase:
    Type: String
    Default: your_database
  SolcastApiKey:
    Type: String
    Default: SOLCAST_API_KEY
